before:
  hooks:
    - go mod download
builds:
- binary: "terraform-provider-proxmox_{{.Tag}}"
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
  env:
    - CGO_ENABLED=0
archives:
- format: gz
  files:
    - none*
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
